baseURL = 'https://www.guptasoham.com/'
languageCode = 'en-us'
title = "Soham's place"
copyright = "Soham Gupta Â©"

[module]
  [module.hugoVersion]
    min = "0.81.0"

[params]
  initials = "SG"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[taxonomies]
  garden_tags = 'garden_tags'
  ai_tags = 'ai_tags'
  law_tags = 'law_tags'
  art_tags = 'art_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
